# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields
import sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('dt_modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('dt_birth', models.DateTimeField(verbose_name='birth date time')),
                ('dt_death', models.DateTimeField(blank=True, null=True, verbose_name='death date time')),
                ('biography', models.TextField(blank=True, verbose_name='biography')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='AuthorPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('dt_modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='logo image', null=True, upload_to='', verbose_name='photo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Author', verbose_name='author')),
            ],
            options={
                'verbose_name': 'author photo',
                'verbose_name_plural': 'author photos',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('dt_modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('score', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='score')),
                ('date_published', models.DateField(verbose_name='date published')),
                ('time_published', models.TimeField(verbose_name='time published')),
                ('preview_sample', models.FileField(blank=True, upload_to='', verbose_name='short preview sample')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name="author's book sequence")),
                ('similar_books_ids', sample.models.PositiveSetField(base_field=models.PositiveIntegerField(validators=[sample.models.positive_integer_validator], verbose_name='similar books IDs'), blank=True, default=list, size=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Author', verbose_name='author')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
