# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'dead'), (255, 'alive'), (30, 'dried')], default=255, verbose_name='state'),
        ),
    ]
