# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import sample.models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_author_inspire_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllModelFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_date', models.DateField(default=sample.models.default_date, verbose_name='date')),
                ('f_time', models.TimeField(default=sample.models.default_time, verbose_name='time')),
                ('f_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time')),
                ('f_integer', models.IntegerField(default=-22, verbose_name='integer')),
                ('f_positive_integer', models.PositiveIntegerField(default=0, verbose_name='positive integer')),
                ('f_small_integer', models.SmallIntegerField(default=13, verbose_name='small integer')),
                ('f_positive_small_integer', models.PositiveSmallIntegerField(default=222, verbose_name='positive small integer')),
                ('f_decimal', models.DecimalField(decimal_places=4, default=3.1415, max_digits=10, verbose_name='decimal')),
                ('f_float', models.FloatField(default=3.14, verbose_name='float')),
                ('f_choice', models.PositiveSmallIntegerField(choices=[(0, 'dead'), (255, 'alive'), (30, 'dried')], default=255, verbose_name='choice')),
                ('f_file', models.FileField(blank=True, upload_to='', verbose_name='short preview sample')),
                ('f_photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='logo image', null=True, upload_to='', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'all model fields',
                'verbose_name_plural': 'list of all model fields instances',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='dt_birth',
            field=models.DateTimeField(help_text='Select the day of birth', verbose_name='birth date time'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Author real name', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='allmodelfields',
            name='f_fk_embed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sample.Author', verbose_name='embedded foreign key'),
        ),
        migrations.AddField(
            model_name='allmodelfields',
            name='f_fk_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sample.Book', verbose_name='foreign key with relation'),
        ),
        migrations.AddField(
            model_name='allmodelfields',
            name='f_m2m_embed',
            field=models.ManyToManyField(blank=True, related_name='_allmodelfields_f_m2m_embed_+', to='sample.Author', verbose_name='embedded M2M'),
        ),
        migrations.AddField(
            model_name='allmodelfields',
            name='f_m2m_rel',
            field=models.ManyToManyField(blank=True, related_name='_allmodelfields_f_m2m_rel_+', to='sample.Author', verbose_name='related M2M'),
        ),
    ]
