# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_author_is_ghostwriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, verbose_name='hidden nickname'),
        ),
    ]
